### ISSUE TITLE
Add function to apply multiplier to food object

### ISSUE THREAD

**Issue by mattsilv** [nutritionix/track-api-angular-client#1]
Example:

Protein Shake has serving qty=12, serving unit=oz, calories=100

If user indicates they had 10oz protein shake, the library would get the multiplier by taking 10/12, and apply that multiplier to all values in the food object.
- [x] library should apply multiplier to all top level nutrition attributes in food object
- [x] library should apply multiplier to all attributes in full_nutrients array

**Comment by Yurko-Fedoriv** [comment]
@mattsilv FYI added helper service with couple useful methods: http://nutritionix.github.io/track-api-angular-client/docs/#/api/nix.track-api-client.service:nixTrackUtils
